all: basic reverse max even project

basic:
	g++ examples/basic_array.cpp -o basic_array && ./basic_array

reverse:
	g++ problems/reverse_array.cpp -o reverse_array && ./reverse_array

max:
	g++ problems/max_element.cpp -o max_element && ./max_element

even:
	g++ problems/even_count.cpp -o even_count && ./even_count

project:
	g++ mini_project/grade_analysis_tool.cpp -o grade_tool && ./grade_tool

clean:
	del *.exe
